[package]
name = "program"
version.workspace = true
edition.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }