[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
sled.workspace = true
tiny-keccak.workspace = true
